// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAutoComplete: typeof import('@arco-design/web-vue')['AutoComplete']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AInput: typeof import('@arco-design/web-vue')['Input']
    Banner: typeof import('./src/components/Banner.vue')['default']
    Description: typeof import('./src/components/Description.vue')['default']
    Greet: typeof import('./src/components/Greet.vue')['default']
    XmPlayer: typeof import('./src/components/Player/XmPlayer.vue')['default']
    XmSearch: typeof import('./src/components/Player/XmSearch.vue')['default']
    XmVideo: typeof import('./src/components/Player/XmVideo.vue')['default']
  }
}
