/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BannerFooter: typeof import('./src/components/Player/BannerFooter.vue')['default']
    BannerHeader: typeof import('./src/components/Player/BannerHeader.vue')['default']
    BannerWrapper: typeof import('./src/components/Player/BannerWrapper.vue')['default']
    HBanner: typeof import('./src/components/HBanner.vue')['default']
    HDescription: typeof import('./src/components/HDescription.vue')['default']
    HGreet: typeof import('./src/components/HGreet.vue')['default']
    HTest: typeof import('./src/components/HTest.vue')['default']
    XmFeedback: typeof import('./src/components/XmFeedback.vue')['default']
    XmHistoryEditDialog: typeof import('./src/components/Player/XmHistoryEditDialog.vue')['default']
    XmPlayer: typeof import('./src/components/Player/XmPlayer.vue')['default']
    XmSearch: typeof import('./src/components/Player/XmSearch.vue')['default']
    XmThemePanel: typeof import('./src/components/Theme/XmThemePanel.vue')['default']
    XmVideo: typeof import('./src/components/Player/XmVideo.vue')['default']
  }
}
