// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAutoComplete: typeof import('@arco-design/web-vue')['AutoComplete']
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdownButton: typeof import('@arco-design/web-vue')['DropdownButton']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    AProgress: typeof import('@arco-design/web-vue')['Progress']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ATooltip: typeof import('@arco-design/web-vue')['Tooltip']
    ATypographyText: typeof import('@arco-design/web-vue')['TypographyText']
    BannerFooter: typeof import('./src/components/Player/BannerFooter.vue')['default']
    BannerHeader: typeof import('./src/components/Player/BannerHeader.vue')['default']
    BannerWrapper: typeof import('./src/components/Player/BannerWrapper.vue')['default']
    HBanner: typeof import('./src/components/HBanner.vue')['default']
    HDescription: typeof import('./src/components/HDescription.vue')['default']
    HGreet: typeof import('./src/components/HGreet.vue')['default']
    HTest: typeof import('./src/components/HTest.vue')['default']
    IconCloudDownload: typeof import('@arco-design/web-vue/es/icon')['IconCloudDownload']
    IconDelete: typeof import('@arco-design/web-vue/es/icon')['IconDelete']
    IconEdit: typeof import('@arco-design/web-vue/es/icon')['IconEdit']
    IconHeart: typeof import('@arco-design/web-vue/es/icon')['IconHeart']
    IconPalette: typeof import('@arco-design/web-vue/es/icon')['IconPalette']
    IconRefresh: typeof import('@arco-design/web-vue/es/icon')['IconRefresh']
    IconThumbUp: typeof import('@arco-design/web-vue/es/icon')['IconThumbUp']
    XmHistoryEditDialog: typeof import('./src/components/Player/XmHistoryEditDialog.vue')['default']
    XmPlayer: typeof import('./src/components/Player/XmPlayer.vue')['default']
    XmSearch: typeof import('./src/components/Player/XmSearch.vue')['default']
    XmThemePanel: typeof import('./src/components/Theme/XmThemePanel.vue')['default']
    XmVideo: typeof import('./src/components/Player/XmVideo.vue')['default']
  }
}
